---

- name: NTP config
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  changed_when: true
  notify: 
  - Restart chronyd

- name: Flush handlers
  meta: flush_handlers