---

- name: Install packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - tftp-server
    - dnsmasq
    - bind-utils
    - haproxy
    - wget
    - tree
    - sshpass
    - httpd
    - httpd-tools
    - podman
    - libselinux-python
    - /root/assets/jq/oniguruma-5.9.5-3.el7.ppc64le.rpm
    - /root/assets/jq/jq-1.6-1.el7.ppc64le.rpm